---
title: Journal.Kim
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
    permalink: "/:title"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Brennan K. Brown
email: mail@brennanbrown.ca
description: 'A personal blog for self-quantification via Beeminder. Powered by Jekyll. '
baseurl: ''
url: https://journal.kim
repository: https://github.com/brennanbrown/journalbar
twitter: https://twitter.com/brennankbrown/
github: https://github.com/brennanbrown
paginate: 6
paginate_path: "/:num/"
port: 4040
kramdown:
  input: GFM
# Google Analytics: Update to GA4 (format: G-XXXXXXXXXX)
# Universal Analytics (UA-) was sunset July 1, 2023
# Get your GA4 ID at: https://analytics.google.com/analytics/web/
google_analytics: UA-54919711-3  # TODO: Replace with GA4 measurement ID
disqus: journal-bar
comments: true
theme: 
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate
permalink: "/:title"
theme_switcher: false
exclude:
- ".jekyll-cache"
- Gemfile
- Gemfile.lock
- vendor
- LICENSE
- README.md
- CNAME
